import pandas as pd
import numpy as np
##################################################################
# our imports
##################################################################
import util_fun as uf
from cstm_models import build_mlp, build_lstm, build_cnn, build_gru, build_logistic, get_model_describtion

# --- Define Model Parameters ---
LOOKBACK = 48   # 48 hours of historical data
HORIZON = 24    # 24 hours of prediction
N_FEATURES = 4  # Q_bar, P_bar, T_bar, H_bar
BATCH_SIZE = 32  # batch size for offline learning
H_BAR_INDEX = 3 # H_bar is the 4th feature (index 3)
EPSILON = 1e-6  # For numerical stability in normalization
MAX_EPOCH = 500
EARLY_STOP = 10
MODELS_DES_EXP_PATH = "results/models_description.txt"

###############################################
####### Read the dataset
###############################################
train_ds = pd.read_csv('dataset/one_station_train_data.csv',parse_dates=[0], index_col=0, dayfirst=True)
test_ds  = pd.read_csv('dataset/one_station_test_data.csv',parse_dates=[0], index_col=0, dayfirst=True)

# ==================== Offline evaluation for multiple models ====================

# Build a list of model builders and how they expect input shapes
model_builders = [
	("MLP", build_mlp, True),        # True -> expects flattened input (seq_len * features)
	("Logistic", build_logistic, True),
	("LSTM", build_lstm, False),     # False -> expects (batch, seq_len, features)
	("GRU", build_gru, False),
	("CNN", build_cnn, False),
]

results = {}

# Prepare models description file (overwrite)
with open(MODELS_DES_EXP_PATH, "w", encoding="utf-8") as f:
	f.write("Models description generated by offline_learn.py\n\n")

# --- Run both strategies and collect results in the same dict ---
for step in [HORIZON, LOOKBACK + HORIZON]:
	step_label = f"s{step}"  # e.g. "s24" or "s72"
	print(f"\n{'='*60}\n  STEP = {step}  ({'original — leakage' if step == HORIZON else 'no leakage'})\n{'='*60}")

	x_train, y_train = uf.create_sequences(train_ds.values.astype(np.float32), LOOKBACK, HORIZON, H_BAR_INDEX, step=step)
	x_test, y_test = uf.create_sequences(test_ds.values.astype(np.float32), LOOKBACK, HORIZON, H_BAR_INDEX, step=step)

	# Prepare testing timestamps
	test_timestamps = []
	for j in range(len(x_test)):
		start_idx = j * step + LOOKBACK
		end_idx = start_idx + HORIZON
		idxs = test_ds.index[start_idx:end_idx]
		test_timestamps.extend(list(idxs))

	for name, builder, needs_flatten in model_builders:
		print(f"\n=== Training & evaluating: {name} ({step_label}) ===")

		# Prepare inputs for this model
		if needs_flatten:
			x_train_in = x_train.reshape(len(x_train), -1)
			x_test_in = x_test.reshape(len(x_test), -1)
			input_size = x_train_in.shape[1]
		else:
			x_train_in = x_train
			x_test_in = x_test
			input_size = N_FEATURES

		# Build model + optimizer + criterion using defaults (can be overridden)
		model, optimizer, criterion = builder(input_size=input_size, output_size=HORIZON)

		# Describe model and save description
		desc = get_model_describtion(model)
		print("\nModel description:\n", desc)
		with open(MODELS_DES_EXP_PATH, "a", encoding="utf-8") as f:
			f.write(f"=== {name}_{step_label} ===\n")
			f.write(desc + "\n\n")

		# Train using the offline helper
		y_true, y_pred, timestamps = uf.train_model_offline(
			x_train_in, y_train, x_test_in, y_test, test_timestamps,
			model, optimizer, criterion,
			batch_size=BATCH_SIZE, max_epoch=MAX_EPOCH, early_Stop_threshold=EARLY_STOP
		)

		results[f"{name}_{step_label}"] = (y_true, y_pred, timestamps)

# Plot and print metrics for all models (testing results)
uf.calculate_metrics_and_plot(results, plot_title="Offline Models Comparison",
							export_metrics=True,
							export_html=True,
							export_file_name= "results/testing/offline/offline_models_testing_results")

# Save predictions to CSV files to be used later in Experiments
uf.export_results_to_csv(results, "results/testing/predictions_vs_true/offline")



